/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.funeraria.view;

import br.com.funeraria.controle.*;
import br.com.funeraria.model.*;

/**
 *
 * @author Luan
 */
public class CadCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadUsuario
     */
    Cliente cliente = new Cliente();
    ClienteDAO clidao =  new ClienteDAO();
    
    public CadCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNascimento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPlano = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuario");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 10, 190, 26);

        jPanel1.setBackground(new java.awt.Color(33, 30, 54));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jButtonNovo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNovo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(12, 13, 80, 23);

        jButtonSalvar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(12, 42, 80, 23);

        jButtonCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(12, 71, 80, 23);

        Editar.setBackground(new java.awt.Color(0, 0, 0));
        Editar.setForeground(new java.awt.Color(255, 255, 255));
        Editar.setText("Editar");
        Editar.setEnabled(false);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPanel1.add(Editar);
        Editar.setBounds(10, 100, 80, 23);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 10, 43, 17);

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(240, 10, 475, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 60, 32, 17);

        jTextFieldCPF.setEnabled(false);
        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCPF);
        jTextFieldCPF.setBounds(240, 50, 181, 30);

        jButtonExcluir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(12, 129, 80, 23);

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableUsuario);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 280, 676, 149);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data de Nascimento:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 100, 144, 17);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jComboBoxSexo.setEnabled(false);
        jPanel1.add(jComboBoxSexo);
        jComboBoxSexo.setBounds(400, 170, 50, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sexo:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 170, 38, 17);

        jTextFieldNascimento.setEnabled(false);
        jTextFieldNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNascimento);
        jTextFieldNascimento.setBounds(610, 90, 110, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CEP:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 100, 33, 17);

        jTextFieldCEP.setEnabled(false);
        jTextFieldCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEPActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCEP);
        jTextFieldCEP.setBounds(240, 90, 86, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cidade:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(430, 50, 52, 20);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bairro:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(510, 140, 48, 17);

        jTextFieldCidade.setEnabled(false);
        jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCidade);
        jTextFieldCidade.setBounds(490, 50, 232, 30);

        jTextFieldBairro.setEnabled(false);
        jPanel1.add(jTextFieldBairro);
        jTextFieldBairro.setBounds(570, 130, 145, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numero:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 100, 57, 17);

        jTextFieldNumero.setEnabled(false);
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNumero);
        jTextFieldNumero.setBounds(400, 90, 50, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rua:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(210, 140, 31, 17);

        jTextFieldRua.setEnabled(false);
        jTextFieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRuaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRua);
        jTextFieldRua.setBounds(250, 130, 244, 30);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefone:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(520, 180, 64, 17);

        jTextFieldTelefone.setEnabled(false);
        jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(590, 170, 124, 30);
        jPanel1.add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(70, 240, 192, 30);

        jButtonPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(270, 243, 90, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Plano:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 170, 50, 18);

        jComboBoxPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronze", "Prata", "Gold" }));
        jComboBoxPlano.setEnabled(false);
        jPanel1.add(jComboBoxPlano);
        jComboBoxPlano.setBounds(260, 170, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 40, 970, 550);

        setSize(new java.awt.Dimension(765, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        cliente.setNome(jTextFieldNome.getText());
        cliente.setCpf(jTextFieldCPF.getText());
        cliente.setCidade(jTextFieldCidade.getText());
        cliente.setCep(Integer.parseInt(jTextFieldCEP.getText()));
        cliente.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
        cliente.setNascimento(jTextFieldNascimento.getText());
        cliente.setSexo((String) jComboBoxSexo.getSelectedItem());
        if(jComboBoxPlano.getSelectedItem().equals("Bronze")){
            cliente.setIdPlano(1);
        } else if(jComboBoxPlano.getSelectedItem().equals("Prata")){
            cliente.setIdPlano(2);
        } else if(jComboBoxPlano.getSelectedItem().equals("Gold")){
            cliente.setIdPlano(3);
        }
        cliente.setRua(jTextFieldRua.getText());
        cliente.setBairro(jTextFieldBairro.getText());
        cliente.setTelefone(Integer.parseInt(jTextFieldTelefone.getText()));
        clidao.salvar(cliente);
        
        jTextFieldNome.setText("");
        jTextFieldCPF.setText("");
        jTextFieldCidade.setText("");
        jTextFieldCEP.setText("");
        jTextFieldNumero.setText("");
        jTextFieldNascimento.setText("");
        jTextFieldRua.setText("");
        jTextFieldBairro.setText("");
        jTextFieldTelefone.setText("");
        
        jButtonSalvar.setEnabled(false);
        jTextFieldNome.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jComboBoxPlano.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCPF.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldRua.setEnabled(false);
        jTextFieldTelefone.setEnabled(false);
        jTextFieldNascimento.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNascimentoActionPerformed

    private void jTextFieldCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEPActionPerformed

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jTextFieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRuaActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        jButtonSalvar.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxPlano.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCPF.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jTextFieldTelefone.setEnabled(true);
        jTextFieldNascimento.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        Editar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        
        cliente.setPesquisa(jTextFieldPesquisar.getText());
        Cliente cli = clidao.buscaCliente(cliente);
        
        jTextFieldNome.setText(cliente.getNome());
        jTextFieldCPF.setText(cliente.getCpf());
        jTextFieldCidade.setText(cliente.getCidade());
        jTextFieldCEP.setText(String.valueOf(cliente.getCep()));
        jTextFieldNumero.setText(String.valueOf(cliente.getNumero()));
        jTextFieldNascimento.setText(cliente.getNascimento());
        jTextFieldRua.setText(cliente.getRua());
        jTextFieldBairro.setText(cliente.getBairro());
        jTextFieldTelefone.setText(String.valueOf(cliente.getTelefone()));
        jComboBoxSexo.setSelectedItem(cliente.getSexo());
        jComboBoxPlano.setSelectedItem(cliente.getIdPlano());
        
        jButtonExcluir.setEnabled(true);
        Editar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        
        jTextFieldNome.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jComboBoxPlano.setEnabled(false);
        jTextFieldCEP.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCPF.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldRua.setEnabled(false);
        jTextFieldTelefone.setEnabled(false);
        jTextFieldNascimento.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxPlano.setEnabled(true);
        jTextFieldCEP.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCPF.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jTextFieldTelefone.setEnabled(true);
        jTextFieldNascimento.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
    }//GEN-LAST:event_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxPlano;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldNascimento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
