/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.funeraria.view;

import br.com.funeraria.controle.PlanoDAO;
import br.com.funeraria.model.Plano;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class CadPlano extends javax.swing.JFrame {

    /**
     * Creates new form CadPlano
    */
    PlanoDAO plan = new PlanoDAO();
    Plano pli = new Plano();
    int flag = 0;
    public CadPlano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        iD = new javax.swing.JPanel();
        Novo = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TipoPlano = new javax.swing.JTextField();
        PesquisarTXTFIELD = new javax.swing.JTextField();
        Pesquisar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePesquisar = new javax.swing.JTable();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IdPlano = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(525, 490));
        setResizable(false);
        getContentPane().setLayout(null);

        iD.setBackground(new java.awt.Color(36, 32, 58));
        iD.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iD.setLayout(null);

        Novo.setBackground(new java.awt.Color(0, 0, 0));
        Novo.setForeground(new java.awt.Color(255, 255, 255));
        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        iD.add(Novo);
        Novo.setBounds(12, 34, 77, 23);

        Salvar.setBackground(new java.awt.Color(0, 0, 0));
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setText("Salvar");
        Salvar.setEnabled(false);
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        iD.add(Salvar);
        Salvar.setBounds(12, 63, 77, 23);

        Cancelar.setBackground(new java.awt.Color(0, 0, 0));
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("Cancelar");
        Cancelar.setEnabled(false);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        iD.add(Cancelar);
        Cancelar.setBounds(12, 92, 75, 23);

        Editar.setBackground(new java.awt.Color(0, 0, 0));
        Editar.setForeground(new java.awt.Color(255, 255, 255));
        Editar.setText("Editar");
        Editar.setEnabled(false);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        iD.add(Editar);
        Editar.setBounds(12, 121, 77, 23);

        Excluir.setBackground(new java.awt.Color(0, 0, 0));
        Excluir.setForeground(new java.awt.Color(255, 255, 255));
        Excluir.setText("Excluir");
        Excluir.setEnabled(false);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        iD.add(Excluir);
        Excluir.setBounds(12, 150, 77, 23);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo do Plano:");
        iD.add(jLabel2);
        jLabel2.setBounds(240, 20, 108, 18);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição:");
        iD.add(jLabel3);
        jLabel3.setBounds(210, 50, 79, 18);

        TipoPlano.setEnabled(false);
        TipoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoPlanoActionPerformed(evt);
            }
        });
        iD.add(TipoPlano);
        TipoPlano.setBounds(350, 10, 150, 30);
        iD.add(PesquisarTXTFIELD);
        PesquisarTXTFIELD.setBounds(40, 200, 140, 30);

        Pesquisar.setBackground(new java.awt.Color(0, 0, 0));
        Pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        iD.add(Pesquisar);
        Pesquisar.setBounds(190, 200, 100, 30);

        jTablePesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTablePesquisar);

        iD.add(jScrollPane4);
        jScrollPane4.setBounds(42, 242, 450, 180);

        jTextFieldDescricao.setEnabled(false);
        iD.add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(300, 50, 200, 140);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");
        iD.add(jLabel4);
        jLabel4.setBounds(310, 210, 18, 18);

        IdPlano.setEnabled(false);
        iD.add(IdPlano);
        IdPlano.setBounds(330, 210, 90, 20);

        getContentPane().add(iD);
        iD.setBounds(0, 40, 523, 435);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("Planos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 50, 20);

        setSize(new java.awt.Dimension(531, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TipoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoPlanoActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        // TODO add your handling code here:
        flag = 1;
        TipoPlano.setText("");
       jTextFieldDescricao.setText("");
        
       TipoPlano.setEnabled(true);
       jTextFieldDescricao.setEnabled(true);
       Salvar.setEnabled(true);
       Editar.setEnabled(false);
       Cancelar.setEnabled(true);
       
       
    
    }//GEN-LAST:event_NovoActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        // TODO add your handling code here:
        if(flag == 1){
        pli.setTipo_plano(TipoPlano.getText());
        pli.setDescricao(jTextFieldDescricao.getText());
        try {
            plan.Salvar(pli);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
       
        
       TipoPlano.setText("");
       jTextFieldDescricao.setText("");
       
       TipoPlano.setEnabled(false);
       jTextFieldDescricao.setEnabled(false);
       Salvar.setEnabled(false);
        } else{
            pli.setIdPlano(Integer.parseInt(IdPlano.getText()));
            pli.setTipo_plano(TipoPlano.getText());
            pli.setDescricao(jTextFieldDescricao.getText());
            plan.editar(pli);
            
            TipoPlano.setText("");
       jTextFieldDescricao.setText("");
       
       TipoPlano.setEnabled(false);
       jTextFieldDescricao.setEnabled(false);
       Salvar.setEnabled(false);
        }
       
       
                
    }//GEN-LAST:event_SalvarActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        // TODO add your handling code here:
        pli.setPesquisar(PesquisarTXTFIELD.getText());
        Plano pla = plan.buscarPlano(pli);
        
        Salvar.setEnabled(false);
        
        TipoPlano.setText(pli.getTipo_plano());
        IdPlano.setText(String.valueOf(pli.getIdPlano()));
        jTextFieldDescricao.setText(pli.getDescricao());
        
        Editar.setEnabled(true);
        Excluir.setEnabled(true);
        
       
    }//GEN-LAST:event_PesquisarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        flag =2;
        Salvar.setEnabled(true);
        Cancelar.setEnabled(true);
        
         TipoPlano.setEnabled(true);
         jTextFieldDescricao.setEnabled(true);
         Salvar.setEnabled(true);
         
         Editar.setEnabled(false);
        Excluir.setEnabled(false);
        Novo.setEnabled(false);
        Cancelar.setEnabled(true);
        
    }//GEN-LAST:event_EditarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        TipoPlano.setEnabled(!true);
       jTextFieldDescricao.setEnabled(!true);
       Salvar.setEnabled(!true);
       Editar.setEnabled(false);
       Excluir.setEnabled(false);
       Cancelar.setEnabled(!true);
    }//GEN-LAST:event_CancelarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            pli.setIdPlano(Integer.parseInt(IdPlano.getText()));
            plan.excluir(pli);
            
        
        }
        TipoPlano.setText("");
       jTextFieldDescricao.setText("");
       IdPlano.setText("");
       
       TipoPlano.setEnabled(false);
       jTextFieldDescricao.setEnabled(false);
       Salvar.setEnabled(false);
    }//GEN-LAST:event_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPlano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JTextField IdPlano;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JTextField PesquisarTXTFIELD;
    private javax.swing.JButton Salvar;
    private javax.swing.JTextField TipoPlano;
    private javax.swing.JPanel iD;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTablePesquisar;
    private javax.swing.JTextField jTextFieldDescricao;
    // End of variables declaration//GEN-END:variables
}
